apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-nas-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.180
    path: /Public/gitea
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-nas-pvc
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: gitea-nas-pv
  storageClassName: ""
