# k3s Cluster Configuration
k3s_version: "v1.28.11+k3s2"

# Proxy Configuration
proxy_env:
  HTTP_PROXY: "http://192.168.50.207:7897"
  HTTPS_PROXY: "http://192.168.50.207:7897"
  NO_PROXY: "127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,10.42.0.0/16,10.43.0.0/16,localhost,*.local"

# APT Mirror
apt_mirror: "mirrors.tuna.tsinghua.edu.cn"
