[k3s_nodes]
# 请将 <SERVER_IP> 替换为您的 Linux 服务器 IP
# 请将 <SSH_USER> 替换为您的 SSH 登录用户名 (例如 root 或 ubuntu)
k3s-master ansible_host=192.168.50.181 ansible_user=zhi ansible_ssh_private_key_file=~/.ssh/id_ed25519_2025
