ingress-nginx:
  controller:
    service:
      type: LoadBalancer  # Allows local LAN access via Node IP
    metrics:
      enabled: true
    admissionWebhooks:
      enabled: false  # Simplified for HomeLab, can enable later
    nodeSelector:
      kubernetes.io/hostname: "ubuntu-jammy"
